/*
 * TablesG.java
 *
 * Created on October 21, 2007, 3:32 PM
 */

package screens;


import java.text.SimpleDateFormat;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import java.util.Calendar;

/**
 *
 * @author  jeo
 */




public class TablesG extends javax.swing.JFrame {
    
    private void drawInterface(){
        //market status table
        String DATE_FORMAT = "HH:mm:ss";
        
        
        //get the current time
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat(DATE_FORMAT);
        String ntime = sdf.format(cal.getTime());
        
        String [] TableColumns = {
            "Currency", "Bid", "Ask", "High", "Low", "Time"
        };
        
        Object [][] Data = {
            {"EUR/USD", new Double(1.42991), new Double(1.43021), new Double(1.43021), new Double(1.42991), ntime}
        };
        
        JTable tb = new JTable(Data, TableColumns);
        
        JScrollPane scp = new JScrollPane(tb);
        
        jTabbedPane1.add("Market",scp);
        
        
        
        
        
        
        
        
        
        //checklist with table
        
        
        String [] TableColumns2 = {
            "Currency", "Bid"};
        
        Object [][] Data2 = {
            {"EUR/USD", Boolean.TRUE}
        };
        
        JTable tb3 = new JTable(Data2, TableColumns2){
            public Class getColumnClass(int column) {
                return getValueAt(0, column).getClass();
            }
        };
        
      
        JScrollPane scp3 = new JScrollPane(tb3);
        
        jTabbedPane1.add("Position",scp3);
        
        pack();
        
    }
    
    /** Creates new form TablesG */
    public TablesG() {
        initComponents();
        
        drawInterface();
        
        
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(241, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablesG().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
    
}
