package gui;

/*
 * UserMenu.java
 *
 * Created on November 20, 2007, 6:02 PM
 */

/**
 *
 * @author  kselik
 */

import javax.swing.*;
import clientnetworking.*;
public class UserMenu extends javax.swing.JPanel {
    ClientNetworkInterface m_cni;
    String[] m_currenciesList;
    String[] m_currencyPairsList;
    JFrame owner;
    JPanel Login;
    
    // Get the available traiding currencies from the ACE system
    private void getCurrencies() {
        String message;
        String args[];
        m_cni.SendMessage("getcurrencies");
        while((message = m_cni.ReceiveMessage()).equals("") && m_cni.isConnected());
        args = message.split(" ");
        
        if(args.length >= 3 && args[0].equals("ok") && args[1].equals("getcurrencies")) {
            m_currenciesList = new String[args.length - 2];
            for(int i = 0; i < args.length - 2; i++) {
                m_currenciesList[i] = args[i + 2];
            }
        } else {
            // Failed to login
            m_cni.SendMessage("logout");
            m_cni.disconnect();
            
            // Go back to LoginPanel
            this.setVisible(false);
            Login.setVisible(true);
            owner.setContentPane(Login);
        }
    }
    
    private String[] getCurrencyPairs() {
        String temp = "";
        for(int i = 0; i < m_currenciesList.length; i++) {
            for(int j = 0; j < m_currenciesList.length; j++) {
                if(i != j) {
                    temp += m_currenciesList[i] + "/" + m_currenciesList[j] + " ";
                }
            }
        }
        return temp.trim().split(" ");
    }
    
    private void FillChoice(java.awt.Choice cho, String[] items) {
        for(int i = 0; i < items.length; i++) {
            cho.addItem(items[i]);
        }
    }
    
    private void UpdatePrices() {
        String message;
        String args[];
        try {
            m_cni.SendMessage("getmarketprice buy " + choMarketOrderCurrencyPair.getSelectedItem());
            while((message = m_cni.ReceiveMessage()).equals("") && m_cni.isConnected());
            
            args = message.split(" ");
            if(args.length > 2 && args[0].equals("ok")) {
                lblCurrentMarketPriceBuy.setText(args[2]);
            } else {
                lblCurrentMarketPriceBuy.setText("");
            }
            
            m_cni.SendMessage("getmarketprice sell " + choMarketOrderCurrencyPair.getSelectedItem());
            while((message = m_cni.ReceiveMessage()).equals("") && m_cni.isConnected());

            args = message.split(" ");
            if(args.length > 2 && args[0].equals("ok")) {
                lblCurrentMarketPriceSell.setText(args[2]);
            } else {
                lblCurrentMarketPriceSell.setText("");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    /** Creates new form UserMenu */
    public UserMenu(JFrame owner, JPanel Login, ClientNetworkInterface cni) {
        this.owner=owner;
        this.Login=Login;
        m_cni = cni;
        initComponents();
        
        // Download the available currencies
        getCurrencies();
        
        // Build up the list of currency pairs available
        m_currencyPairsList = getCurrencyPairs();
        
        FillChoice(choMarketOrderCurrencyPair, m_currencyPairsList);
        FillChoice(choLimitOrderCurrencyPair, m_currencyPairsList);
        FillChoice(choStopLossCurrencyPair, m_currencyPairsList);
        FillChoice(choTrailingStopCurrencyPair, m_currencyPairsList);
        
        String[] expiry = {"24 hours", "48 hours", "72 hours"};
        
        FillChoice(choMarketOrderExpiry, expiry);
        FillChoice(choLimitOrderExpiry, expiry);
        FillChoice(choStopLossExpiry, expiry);
        FillChoice(choTrailingStopExpiry, expiry);
        
        // Download the current market prices
        UpdatePrices();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        btnMarketOrderBuy = new javax.swing.JButton();
        btnMarketOrderSell = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtMarketOrderAmount = new javax.swing.JTextField();
        choMarketOrderExpiry = new java.awt.Choice();
        choMarketOrderCurrencyPair = new java.awt.Choice();
        jLabel2 = new javax.swing.JLabel();
        lblCurrentMarketPriceBuy = new javax.swing.JLabel();
        lblCurrentMarketPriceSell = new javax.swing.JLabel();
        btnUpdatePrice = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtLimitOrderAmount = new javax.swing.JTextField();
        txtLimitOrderLimit = new javax.swing.JTextField();
        btnLimitOrderBuy = new javax.swing.JButton();
        btnLimitOrderSell = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        choLimitOrderExpiry = new java.awt.Choice();
        choLimitOrderCurrencyPair = new java.awt.Choice();
        jLabel20 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        choStopLossExpiry = new java.awt.Choice();
        choStopLossCurrencyPair = new java.awt.Choice();
        jLabel18 = new javax.swing.JLabel();
        TrailingStop = new javax.swing.JPanel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        choTrailingStopCurrencyPair = new java.awt.Choice();
        jLabel13 = new javax.swing.JLabel();
        choTrailingStopExpiry = new java.awt.Choice();
        btnLogout = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        UserInfo = new javax.swing.JButton();
        btnOrders = new javax.swing.JButton();

        btnMarketOrderBuy.setText("Buy");
        btnMarketOrderBuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMarketOrderBuyMouseClicked(evt);
            }
        });

        btnMarketOrderSell.setText("Sell");
        btnMarketOrderSell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMarketOrderSellMouseClicked(evt);
            }
        });

        jLabel6.setText("Currency Pair:");

        jLabel5.setText("Expiry:");

        jLabel19.setText("Amount:");

        txtMarketOrderAmount.setText("100000");

        jLabel2.setText("Current Market Price:");

        btnUpdatePrice.setText("Update Prices");
        btnUpdatePrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdatePriceMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(41, 41, 41)
                        .addComponent(lblCurrentMarketPriceBuy)
                        .addGap(50, 50, 50)
                        .addComponent(lblCurrentMarketPriceSell)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                        .addComponent(btnUpdatePrice))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnMarketOrderBuy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMarketOrderSell))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(choMarketOrderCurrencyPair, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel5))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(choMarketOrderExpiry, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                            .addComponent(txtMarketOrderAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE))))
                .addGap(29, 29, 29))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblCurrentMarketPriceBuy)
                    .addComponent(lblCurrentMarketPriceSell)
                    .addComponent(btnUpdatePrice))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(choMarketOrderCurrencyPair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtMarketOrderAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(choMarketOrderExpiry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMarketOrderSell)
                            .addComponent(btnMarketOrderBuy)))
                    .addComponent(jLabel5))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jTabbedPane1.addTab("Market Order", jPanel3);

        txtLimitOrderAmount.setText("100000");

        txtLimitOrderLimit.setText("1.20");

        btnLimitOrderBuy.setText("Buy");
        btnLimitOrderBuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimitOrderBuyMouseClicked(evt);
            }
        });

        btnLimitOrderSell.setText("Sell");
        btnLimitOrderSell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimitOrderSellMouseClicked(evt);
            }
        });

        jLabel14.setText("Amount:");

        jLabel15.setText("Limit:");

        jLabel12.setText("Expiry:");

        jLabel20.setText("Currency Pair:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnLimitOrderBuy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimitOrderSell))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLimitOrderLimit, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                            .addComponent(choLimitOrderExpiry, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                            .addComponent(txtLimitOrderAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                            .addComponent(choLimitOrderCurrencyPair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(choLimitOrderCurrencyPair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(txtLimitOrderAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLimitOrderLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(choLimitOrderExpiry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLimitOrderBuy)
                            .addComponent(btnLimitOrderSell)))
                    .addComponent(jLabel12))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        jTabbedPane1.addTab("Limit Order", jPanel2);

        jTextField3.setEnabled(false);

        jLabel3.setText("Amount:");

        jTextField4.setEnabled(false);

        jLabel4.setText("Stop Loss:");

        jButton3.setText("Buy");
        jButton3.setEnabled(false);

        jButton4.setText("Sell");
        jButton4.setEnabled(false);

        jLabel1.setText("Expiry:");

        choStopLossExpiry.setEnabled(false);

        choStopLossCurrencyPair.setEnabled(false);

        jLabel18.setText("Currency Pair:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel18)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                            .addComponent(choStopLossExpiry, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING, 0, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(choStopLossCurrencyPair, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(choStopLossCurrencyPair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(choStopLossExpiry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        jTabbedPane1.addTab("Stop Loss", jPanel1);

        jButton7.setText("Buy");
        jButton7.setEnabled(false);

        jButton8.setText("Sell");
        jButton8.setEnabled(false);

        jLabel10.setText("Amount:");

        jLabel11.setText("Trailing Points:");

        jTextField1.setEditable(false);

        jTextField2.setEditable(false);

        jLabel16.setText("Currency Pair:");

        choTrailingStopCurrencyPair.setEnabled(false);

        jLabel13.setText("Expiry:");

        choTrailingStopExpiry.setEnabled(false);

        javax.swing.GroupLayout TrailingStopLayout = new javax.swing.GroupLayout(TrailingStop);
        TrailingStop.setLayout(TrailingStopLayout);
        TrailingStopLayout.setHorizontalGroup(
            TrailingStopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrailingStopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TrailingStopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TrailingStopLayout.createSequentialGroup()
                        .addGroup(TrailingStopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TrailingStopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel16)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TrailingStopLayout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(TrailingStopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                            .addComponent(choTrailingStopCurrencyPair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                            .addComponent(choTrailingStopExpiry, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)))
                    .addGroup(TrailingStopLayout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TrailingStopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField11, javax.swing.GroupLayout.Alignment.TRAILING, 0, 0, Short.MAX_VALUE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.Alignment.TRAILING, 0, 0, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );
        TrailingStopLayout.setVerticalGroup(
            TrailingStopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrailingStopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TrailingStopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(choTrailingStopCurrencyPair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TrailingStopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TrailingStopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(TrailingStopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(TrailingStopLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(TrailingStopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(choTrailingStopExpiry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(TrailingStopLayout.createSequentialGroup()
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(TrailingStopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton8)
                                    .addComponent(jButton7))))))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jTabbedPane1.addTab("Trailing Stop", TrailingStop);

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jButton2.setText("Liquidate");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        UserInfo.setText("User Info");
        UserInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserInfoActionPerformed(evt);
            }
        });

        btnOrders.setLabel("Orders");
        btnOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLogout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                        .addComponent(UserInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOrders)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogout)
                    .addComponent(btnOrders)
                    .addComponent(UserInfo)
                    .addComponent(jButton2))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdatePriceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdatePriceMouseClicked
        UpdatePrices();
    }//GEN-LAST:event_btnUpdatePriceMouseClicked

    private void btnLimitOrderSellMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimitOrderSellMouseClicked
        String message;
        String args[];
        try {
            // Example: placelimitorder [buy/sell] [currencypair] [amount] [price] [number of hours before expires] [limit (pts)]
            m_cni.SendMessage("placelimitorder sell " + choMarketOrderCurrencyPair.getSelectedItem() + " " + txtLimitOrderAmount.getText() + " " + lblCurrentMarketPriceSell.getText() + " " + choLimitOrderExpiry.getSelectedItem().split(" ")[0] + " " + txtLimitOrderLimit.getText());
            while((message = m_cni.ReceiveMessage()).equals("") && m_cni.isConnected());
            
            args = message.split(" ");
            if(args.length >= 1 && args[0].equals("ok")) {
                JOptionPane.showMessageDialog(new JFrame(), "Your limit order has been placed.");
            } else {
                JOptionPane.showMessageDialog(new JFrame(), "The limit order could not be commited by the server.");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnLimitOrderSellMouseClicked

    private void btnLimitOrderBuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimitOrderBuyMouseClicked
        String message;
        String args[];
        try {
            // Example: placelimitorder [buy/sell] [currencypair] [amount] [price] [number of hours before expires] [limit (pts)]
            m_cni.SendMessage("placelimitorder buy " + choMarketOrderCurrencyPair.getSelectedItem() + " " + txtLimitOrderAmount.getText() + " " + lblCurrentMarketPriceSell.getText() + " " + choLimitOrderExpiry.getSelectedItem().split(" ")[0] + " " + txtLimitOrderLimit.getText());
            while((message = m_cni.ReceiveMessage()).equals("") && m_cni.isConnected());
            
            args = message.split(" ");
            if(args.length >= 1 && args[0].equals("ok")) {
                JOptionPane.showMessageDialog(new JFrame(), "Your limit order has been placed.");
            } else {
                JOptionPane.showMessageDialog(new JFrame(), "The limit order could not be commited by the server.");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnLimitOrderBuyMouseClicked

    private void btnMarketOrderSellMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMarketOrderSellMouseClicked
        String message;
        String args[];
        try {
            m_cni.SendMessage("placemarketorder sell " + choMarketOrderCurrencyPair.getSelectedItem() + " " + txtMarketOrderAmount.getText() + " " + lblCurrentMarketPriceSell.getText() + " " + choMarketOrderExpiry.getSelectedItem().split(" ")[0]);
            while((message = m_cni.ReceiveMessage()).equals("") && m_cni.isConnected());
            
            args = message.split(" ");
            if(args.length >= 1 && args[0].equals("ok")) {
                JOptionPane.showMessageDialog(new JFrame(), "Your market order has been placed.");
            } else {
                JOptionPane.showMessageDialog(new JFrame(), "The market order could not be commited by the server.");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnMarketOrderSellMouseClicked

    private void btnMarketOrderBuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMarketOrderBuyMouseClicked
        String message;
        String args[];
        try {
            m_cni.SendMessage("placemarketorder buy " + choMarketOrderCurrencyPair.getSelectedItem() + " " + txtMarketOrderAmount.getText() + " " + lblCurrentMarketPriceBuy.getText() + " " + choMarketOrderExpiry.getSelectedItem().split(" ")[0]);
            while((message = m_cni.ReceiveMessage()).equals("") && m_cni.isConnected());
            
            args = message.split(" ");
            if(args.length >= 1 && args[0].equals("ok")) {
                JOptionPane.showMessageDialog(new JFrame(), "Your market order has been placed.");
            } else {
                JOptionPane.showMessageDialog(new JFrame(), "The market order could not be commited by the server.");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnMarketOrderBuyMouseClicked

    private void btnOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdersActionPerformed
      TabbedPane2 order = new TabbedPane2(this, owner, m_cni);
      this.setVisible(false);
      owner.setContentPane(order);
      order.setVisible(true);
    }//GEN-LAST:event_btnOrdersActionPerformed

    private void UserInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserInfoActionPerformed
        TabbedPane1 pane = new TabbedPane1(this, owner, m_cni);
        this.setVisible(false);
        owner.setContentPane(pane);
        pane.setVisible(true);
    }//GEN-LAST:event_UserInfoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        try {
            if(m_cni.isConnected()) {
                m_cni.SendMessage("logout");
                m_cni.disconnect();
            }
            this.setVisible(false);
            Login.setVisible(true);
            owner.setContentPane(Login);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TrailingStop;
    private javax.swing.JButton UserInfo;
    private javax.swing.JButton btnLimitOrderBuy;
    private javax.swing.JButton btnLimitOrderSell;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMarketOrderBuy;
    private javax.swing.JButton btnMarketOrderSell;
    private javax.swing.JButton btnOrders;
    private javax.swing.JButton btnUpdatePrice;
    private java.awt.Choice choLimitOrderCurrencyPair;
    private java.awt.Choice choLimitOrderExpiry;
    private java.awt.Choice choMarketOrderCurrencyPair;
    private java.awt.Choice choMarketOrderExpiry;
    private java.awt.Choice choStopLossCurrencyPair;
    private java.awt.Choice choStopLossExpiry;
    private java.awt.Choice choTrailingStopCurrencyPair;
    private java.awt.Choice choTrailingStopExpiry;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lblCurrentMarketPriceBuy;
    private javax.swing.JLabel lblCurrentMarketPriceSell;
    private javax.swing.JTextField txtLimitOrderAmount;
    private javax.swing.JTextField txtLimitOrderLimit;
    private javax.swing.JTextField txtMarketOrderAmount;
    // End of variables declaration//GEN-END:variables
    
}
