package gui;
/*
 * AdminChangePassword.java
 *
 * Created on November 30, 2007, 5:44 PM
 */

/**
 *
 * @author  icioba1
 */


import javax.swing.*;
import clientnetworking.*;

public class AdminChangePassword extends javax.swing.JPanel {
        JFrame owner;
        JPanel admin;
        ClientNetworkInterface m_cni;
    
    /** Creates new form AdminChangePassword */
    public AdminChangePassword(JFrame owner, JPanel admin, ClientNetworkInterface cni ) {
        
        this.owner=owner;
        this.admin=admin;
        m_cni = cni;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        newpw1 = new javax.swing.JPasswordField();
        newpw2 = new javax.swing.JPasswordField();
        btnCancel = new javax.swing.JButton();

        jLabel2.setText("Password:");

        jLabel3.setText("Password again:");

        btnSubmit.setText("Submit");
        btnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubmitMouseClicked(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(109, 109, 109)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(btnCancel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnSubmit))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel2)
                            .add(jLabel3))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(newpw2)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, newpw1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(388, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(113, 113, 113)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(newpw1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(newpw2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnSubmit)
                    .add(btnCancel))
                .addContainerGap(351, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
            admin.setVisible(true);
            owner.setContentPane(admin);
            this.setVisible(false);
    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseClicked
        String password1 = newpw1.getText();
        String password2 = newpw2.getText();
        
        if(password1.equals(password2) && password1.indexOf(" ") < 0){
            String message;
            
            // Verify that the admin is still connected
            if(m_cni.isConnected()) {
                // Send request
                m_cni.SendMessage("changepassword " + password1);
                while((message = m_cni.ReceiveMessage()).equals("") && m_cni.isConnected());
                
                if(message.equals("ok changepassword")) {
                    // Go to AdminMenu
                    admin.setVisible(true);
                    owner.setContentPane(admin);
                    this.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(new JFrame(), "Change password request failed.");
                }
            } else {
                // Error message
                JOptionPane.showMessageDialog(new JFrame(), "You are not connected to the server.");
            }
        } else {
            // Error message
            JOptionPane.showMessageDialog(new JFrame(), "The password are not identical. Please enter two identical passwords.");
        }

    }//GEN-LAST:event_btnSubmitMouseClicked
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField newpw1;
    private javax.swing.JPasswordField newpw2;
    // End of variables declaration//GEN-END:variables
    
}
