package gui;
/*
 * UserCreation.java
 *
 * Created on November 30, 2007, 5:47 PM
 */

/**
 *
 * @author  icioba1
 */

import javax.swing.*;
import clientnetworking.*;

public class UserCreation extends javax.swing.JPanel {
    JFrame owner;
    JPanel admin;
    ClientNetworkInterface m_cni;
    
    /** Creates new form UserCreation */
    public UserCreation(JFrame owner, JPanel admin, ClientNetworkInterface cni) {
        this.owner=owner;
        this.admin=admin;
        m_cni = cni;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        pwdPassword = new javax.swing.JPasswordField();
        Cancel = new javax.swing.JButton();

        jLabel1.setText("Username:");

        jLabel2.setText("Password:");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        Cancel.setText("Cancel");
        Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel1)
                            .add(jLabel2))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(pwdPassword, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .add(txtUsername, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(13, 13, 13)
                        .add(Cancel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnSubmit)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(txtUsername, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(pwdPassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 29, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Cancel)
                    .add(btnSubmit))
                .add(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseClicked
      // Go to AdminMenu
      admin.setVisible(true);
      owner.setContentPane(admin);
      this.setVisible(false);
    }//GEN-LAST:event_CancelMouseClicked

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        String message;
        
        // Validate username and password
        String username = txtUsername.getText();
        if(username.length() > 0 && username.indexOf(" ") < 0) {
            
            String password = pwdPassword.getText();
            if(password.length() > 0 && password.indexOf(" ") < 0) {

                // Check that admin is still connected
                if(m_cni.isConnected()) {
                    // Send the create end-user request
                    m_cni.SendMessage("createaccount " + username + " " + password);
                    
                    while((message = m_cni.ReceiveMessage()).equals("") && m_cni.isConnected());
                    
                    // If an error occurs during the creation of the account
                    if(message.equals("ok createaccount " + username)) {
                        // Go to AdminMenu
                        admin.setVisible(true);
                        owner.setContentPane(admin);
                        this.setVisible(false);
                    } else {
                        JOptionPane.showMessageDialog(new JFrame(), "The new account could not be created.");
                    }
                }
            } else {
                // Invalid password
                JOptionPane.showMessageDialog(new JFrame(), "Invalid password.");
            }
        } else {
            // Invalid username
            JOptionPane.showMessageDialog(new JFrame(), "Invalid username.");
        }
    }//GEN-LAST:event_btnSubmitActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField pwdPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
    
}
